[package]
name = "ukonf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos.workspace = true
lalrpop-util = "0.19.8"
serde_json.workspace = true
serde_yaml.workspace = true

[build-dependencies]
lalrpop = "0.19.8"