[package]
name = "upsilon-difftests"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true

git2.workspace = true

rustc-demangle = "0.1.21"

serde.workspace = true
serde_json.workspace = true

upsilon-difftests-core.workspace = true
