[package]
name = "upsilon-ssh-russh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
russh = { version = "0.35.0-beta.8", features = ["openssl"] }
russh-keys = { version = "0.23.0-beta.1", features = ["openssl"] }
thiserror.workspace = true
tokio.workspace = true
humantime.workspace = true
serde.workspace = true
log.workspace = true
path-slash.workspace = true

upsilon-ssh.workspace = true
upsilon-core.workspace = true