[package]
name = "ukonf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
lalrpop-util.workspace = true
logos.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
thiserror.workspace = true

[dev-dependencies]
upsilon-json-diff.workspace = true

[build-dependencies]
lalrpop.workspace = true