[package]
name = "setup_testenv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
upsilon-test-support.workspace = true
pretty_env_logger.workspace = true
log.workspace = true
git2.workspace = true