[alias]
xtask = "run --package upsilon-xtask --bin upsilon-xtask --"
x = "xtask"
xr = "x r"
xt = "x t"
xf = "x fmt"
xfc = "x fmt-check"
xd = "x d"
xgen-ws-layout = "run --package upsilon-xtask --bin gen_ws_layout"
ush = "run --package upsilon-shell --bin upsilon-shell --"

[target.'cfg(all())']
rustflags = [
    "--cfg", "uuid_unstable",
    "-Zshare-generics=y",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-Clink-arg=-fuse-ld=lld",
]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.x86_64-apple-darwin]
rustflags = [
    "-Csplit-debuginfo=unpacked",
]

[profile.dev]
opt-level = 0
debug = 2
incremental = true
codegen-units = 512

[profile.release]
opt-level = 3
debug = 0
incremental = false
codegen-units = 256

[profile.difftests]
inherits = "dev"
rustflags = [
    "-C", "instrument-coverage",
    "--cfg", "testcoverage",
    "--cfg", "difftests",
    "--cfg", "cargo_difftests",
]

[profile.ci]
inherits = "dev"

[unstable]
profile-rustflags = true