[alias]
xtask = "run --package upsilon-xtask --"

[build]
rustflags = ["--cfg", "uuid_unstable"]
[target.x86_64-unknown-linux-gnu]
rustflags = [
    "--cfg", "uuid_unstable",
    "-Clink-arg=-fuse-ld=lld",
    "-Zshare-generics=y",
]

[target.x86_64-pc-windows-msvc]
rustflags = [
    "--cfg", "uuid_unstable",
    "-Zshare-generics=y"
]
linker = "rust-lld.exe"

[target.x86_64-apple-darwin]
rustflags = [
    "--cfg", "uuid_unstable",
    "-C",
    "-Zshare-generics=y",
    "-Csplit-debuginfo=unpacked",
]
[profile.dev]
opt-level = 0
debug = 2
incremental = true
codegen-units = 512

[profile.release]
opt-level = 3
debug = 0
incremental = false
codegen-units = 256
split-debuginfo = "..."
