[package]
name = "upsilon-plugin-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

upsilon-plugin-core.workspace = true
