[package]
name = "upsilon-xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
cargo.workspace = true
cargo-cranky.workspace = true
cargo-difftests.workspace = true
clap.workspace = true
fs_extra.workspace = true
git2.workspace = true
glob.workspace = true
lazy_static.workspace = true
log.workspace = true
path-absolutize.workspace = true
path-slash.workspace = true
pretty_env_logger.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
toml_edit.workspace = true
ukonf.workspace = true
zip.workspace = true

upsilon-diff-util.workspace = true

[[bin]]
name = "upsilon-xtask"
path = "src/bin/upsilon-xtask/main.rs"
