[package]
name = "cargo-cranky"
authors = ["Eric Seppanen <eds@reric.net>"]
description = "Easy to configure wrapper for clippy"
keywords = ["cargo", "clippy", "lint", "lints"]
categories = ["development-tools::cargo-plugins"]
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ericseppanen/cargo-cranky"
readme = "README.md"
rust-version = "1.56"

[dependencies]
anyhow.workspace = true
cargo.workspace = true
clap.workspace = true
serde.workspace = true
toml.workspace = true

[package.metadata.release]
dev-version = false
pre-release-commit-message = "release {{version}}"
