[package]
name = "cargo-difftests-core"
version = "0.1.0-alpha.1"
edition = "2021"
description = "cargo-difftests: core library"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
