[package]
name = "spec-serde"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spec = { path = "../spec" }
quote = "1.0.21"
proc-macro2 = "1.0.47"