name: Publish docs
on:
  push:
    branches:
    - trunk
    paths:
    - docs/**
    - .github/workflows/publish-docs.yaml
env:
  CARGO_TERM_COLOR: always
jobs:
  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install lld
      run: sudo apt-get install -y lld
    - name: Install rust
      run: rustup update nightly && rustup default nightly
    - name: Install mdbook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: latest
    - name: Run xtask build-docs
      run: cargo xtask build-docs
    - name: Add CNAME
      run: echo "upsilon-docs.dnbln.dev" > ./docs/book/CNAME
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/book
