name: Publish docs

on:
  push:
    branches: [ "trunk" ]
    paths:
      - 'docs/**'
      - '.github/workflows/publish-docs.yaml'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-docs:
    name: "Publish docs"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install lld
        run: sudo apt-get install -y lld
      - name: Install rust
        run: rustup update nightly && rustup default nightly
      - name: Install mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"
      - name: Setup git identity
        run: |
          git config --global user.name "Dinu Blanovschi"
          git config --global user.email "git@dnbln.dev"
      - name: Run xtask publish-docs
        run: cargo xtask publish-docs
