name: Test
on:
  push:
    branches:
    - trunk
    paths:
    - crates/**
    - dev/**
    - Cargo.toml
    - Cargo.lock
    - rustfmt.toml
    - clippy.toml
    - .cargo/**
    - .ci/github-workflows/**
    - .config/nextest.toml
    - .github/workflows/test.yaml
    - schemas/graphql/schema.graphql
  pull_request:
    branches:
    - trunk
env:
  CARGO_TERM_COLOR: always
jobs:
  compile-xtask-linux:
    name: Compile xtask (Linux)
    runs-on: ubuntu-latest
    env:
      UXTASK_USE_GLOBAL_CARGO: '1'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install lld
      run: sudo apt-get install -y lld
    - name: Install rust
      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
    - name: Compile xtask
      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
    - name: Copy xtask to artifact
      run: mkdir -p ./ci-artifacts && cp target/debug/upsilon-xtask ./ci-artifacts/upsilon-xtask
    - name: Upload xtask
      uses: actions/upload-artifact@v3
      with:
        name: ${{ runner.os }}-xtask
        path: ./ci-artifacts/upsilon-xtask
  style-checks:
    name: Style checks
    runs-on: ubuntu-latest
    needs: compile-xtask-linux
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install lld
      run: sudo apt-get install -y lld
    - name: Install rust
      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Download xtask
      uses: actions/download-artifact@v3
      with:
        name: ${{ runner.os }}-xtask
        path: ./ci-artifacts/downloaded-xtask
    - name: Copy downloaded xtask to artifact path
      run: mkdir -p ./ci-artifacts && cp ./ci-artifacts/downloaded-xtask/upsilon-xtask ./ci-artifacts/upsilon-xtask && chmod +x ./ci-artifacts/upsilon-xtask
    - name: Run fmt check
      run: ./ci-artifacts/upsilon-xtask fmt-check
    - name: Git checks
      run: ./ci-artifacts/upsilon-xtask git-checks --checkout
      if: success() || failure()
    - name: Check Cargo.toml dependencies order
      run: ./ci-artifacts/upsilon-xtask check-cargo-dep-order
      if: success() || failure()
    - name: Check Cargo.toml dependencies from workspace.dependencies
      run: ./ci-artifacts/upsilon-xtask check-cargo-dep-from-workspace
      if: success() || failure()
  gql-schema-up-to-date:
    name: GraphQL schema is up-to-date
    runs-on: ubuntu-latest
    needs: compile-xtask-linux
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install lld
      run: sudo apt-get install -y lld
    - name: Install rust
      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
    - name: Download xtask
      uses: actions/download-artifact@v3
      with:
        name: ${{ runner.os }}-xtask
        path: ./ci-artifacts/downloaded-xtask
    - name: Copy downloaded xtask to artifact path
      run: mkdir -p ./ci-artifacts && cp ./ci-artifacts/downloaded-xtask/upsilon-xtask ./ci-artifacts/upsilon-xtask && chmod +x ./ci-artifacts/upsilon-xtask
    - name: Run gql schema check
      run: ./ci-artifacts/upsilon-xtask graphql-schema-check
  ci-files-up-to-date:
    name: CI files are up-to-date
    runs-on: ubuntu-latest
    needs: compile-xtask-linux
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install lld
      run: sudo apt-get install -y lld
    - name: Install rust
      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
    - name: Download xtask
      uses: actions/download-artifact@v3
      with:
        name: ${{ runner.os }}-xtask
        path: ./ci-artifacts/downloaded-xtask
    - name: Copy downloaded xtask to artifact path
      run: mkdir -p ./ci-artifacts && cp ./ci-artifacts/downloaded-xtask/upsilon-xtask ./ci-artifacts/upsilon-xtask && chmod +x ./ci-artifacts/upsilon-xtask
    - name: Run ci files up to date check
      run: ./ci-artifacts/upsilon-xtask check-ci-files-up-to-date
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: compile-xtask-linux
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install lld
      run: sudo apt-get install -y lld
    - name: Install openssl
      run: sudo apt-get install -y libssl-dev
    - name: Install rust
      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
    - name: Install clippy
      run: rustup component add clippy
    - name: Download xtask
      uses: actions/download-artifact@v3
      with:
        name: ${{ runner.os }}-xtask
        path: ./ci-artifacts/downloaded-xtask
    - name: Copy downloaded xtask to artifact path
      run: mkdir -p ./ci-artifacts && cp ./ci-artifacts/downloaded-xtask/upsilon-xtask ./ci-artifacts/upsilon-xtask && chmod +x ./ci-artifacts/upsilon-xtask
    - name: Lint
      run: ./ci-artifacts/upsilon-xtask lint
  compile-openssl-win:
    name: Compile openssl (Windows)
    runs-on: windows-latest
    steps:
    - name: Setup env
      run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Restore built openssl
      id: restore_build_openssl
      uses: actions/cache/restore@v3
      env:
        OPENSSL_TRIPLE: x64-windows-static-md
      with:
        path: ${{ env.VCPKG_ROOT }}\installed\${{ env.OPENSSL_TRIPLE }}
        key: build-openssl-win
    - name: Install openssl
      run: vcpkg install openssl:x64-windows-static-md
      if: steps.restore_build_openssl.outputs.cache-hit != 'true'
    - name: Save built openssl
      uses: actions/cache/save@v3
      env:
        OPENSSL_TRIPLE: x64-windows-static-md
      with:
        path: ${{ env.VCPKG_ROOT }}\installed\${{ env.OPENSSL_TRIPLE }}
        key: build-openssl-win
      if: steps.restore_build_openssl.outputs.cache-hit != 'true'
    - name: Upload openssl artifacts
      uses: actions/upload-artifact@v3
      env:
        OPENSSL_TRIPLE: x64-windows-static-md
      with:
        name: openssl-artifacts
        path: ${{ env.VCPKG_ROOT }}\installed\${{ env.OPENSSL_TRIPLE }}\*
        if-no-files-found: error
  test-win:
    name: Test (Windows)
    runs-on: windows-latest
    needs: compile-openssl-win
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup env
      run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Restore built openssl
      uses: actions/download-artifact@v3
      with:
        path: target\openssl
        name: openssl-artifacts
    - name: List downloaded openssl directory structure
      run: ls -R target\openssl
    - name: Set up openssl env
      run: echo "OPENSSL_DIR=$(Get-Location)\target\openssl" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Install rust
      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Print environment
      shell: pwsh
      run: 'ls env:'
    - name: Collect other system information
      run: "\n          git --version\n        "
    - name: Compile xtask
      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
    - name: Compile binaries and tests
      run: cargo xtask test --verbose --no-run --profile ci --custom-bin-dir ./bin-dir
    - name: Run tests
      run: cargo xtask test --verbose --no-fail-fast --profile ci --no-build-dev --custom-bin-dir ./bin-dir
    - name: Run doctests
      run: cargo xtask test --verbose --no-fail-fast --doc --profile ci
  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install lld
      run: sudo apt-get install -y lld
    - name: Install openssl
      run: sudo apt-get install -y libssl-dev
    - name: Install rust
      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Print environment
      run: "\n          env\n        "
    - name: Collect other system information
      run: "\n          git --version\n        "
    - name: Compile xtask
      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
    - name: Compile binaries and tests
      run: cargo xtask test --verbose --no-run --profile ci --custom-bin-dir ./bin-dir
    - name: Run tests
      run: cargo xtask test --verbose --no-fail-fast --profile ci --no-build-dev --custom-bin-dir ./bin-dir
    - name: Run doctests
      run: cargo xtask test --verbose --no-fail-fast --doc --profile ci
  test-linux-with-difftests:
    name: Test (Linux with difftests)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Install lld
      run: sudo apt-get install -y lld
    - name: Install openssl
      run: sudo apt-get install -y libssl-dev
    - name: Install rust
      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Print environment
      run: "\n          env\n        "
    - name: Collect other system information
      run: "\n          git --version\n        "
    - name: Compile xtask
      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
    - name: Compile binaries and tests (with difftests)
      run: cargo xtask test --verbose --no-run --profile difftests --custom-bin-dir ./bin-dir
    - name: Run tests (with difftests)
      run: cargo xtask test --verbose --no-fail-fast --profile difftests --no-build-dev --custom-bin-dir ./bin-dir
  test-linux-only-difftests:
    name: Test (Linux only difftests)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0
    - name: Get old commit
      id: get-old-commit
      run: "\n    if [ \"$PUSH_BEFORE\" != \"\" ]; then\n        echo \"OLD_COMMIT=$PUSH_BEFORE\" >> $GITHUB_OUTPUT\n    else\n        if [ \"$PULL_REQUEST_BASE_SHA\" != \"\" ]; then\n            echo \"OLD_COMMIT=$PULL_REQUEST_BASE_SHA\" >> $GITHUB_OUTPUT\n        else\n            echo \"Error: neither PUSH_BEFORE nor PULL_REQUEST_BASE_SHA is set\" >&2\n            exit 1\n        fi\n    fi\n  "
      env:
        PUSH_BEFORE: ${{ github.event.before }}
        PULL_REQUEST_BASE_SHA: ${{ github.event.pull_request.base.sha }}
    - name: Install lld
      run: sudo apt-get install -y lld
    - name: Install openssl
      run: sudo apt-get install -y libssl-dev
    - name: Install rust
      run: rustup toolchain install nightly-2023-02-03 --no-self-update && rustup default nightly-2023-02-03
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Print environment
      run: "\n          env\n        "
    - name: Collect other system information
      run: "\n          git --version\n        "
    - name: Compile xtask
      run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
    - name: Compile binaries and tests (with difftests)
      run: cargo xtask test --verbose --no-run --profile difftests --custom-bin-dir ./bin-dir
    - name: Run tests (only difftests)
      run: cargo xtask test-quick --from-index --verbose --no-fail-fast --profile difftests --algo git-diff-files --commit ${{ steps.get-old-commit.outputs.OLD_COMMIT }}
