name: Test

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Install lld"
        run: sudo apt-get install -y lld
      - name: "Install rust"
        run: rustup update nightly && rustup default nightly
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo x test --verbose
