name: Test

on:
  push:
    branches: [ "trunk" ]
    paths:
      - 'crates/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - 'rustfmt.toml'
      - 'clippy.toml'
      - '.cargo/**'
      - '.config/nextest.toml'
      - '.github/workflows/test.yaml'
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  style-checks:
    name: Style checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # By default actions/checkout checks out a merge commit. Check out the PR head instead.
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install lld
        run: sudo apt-get install -y lld
      - name: Install rust
        run: rustup update nightly && rustup default nightly
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Compile xtask
        run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
      - name: Run fmt check
        run: cargo xtask fmt-check
      - name: Git checks
        run: cargo xtask git-checks --checkout
      - name: Check Cargo.toml dependencies order
        run: cargo xtask check-cargo-dep-order
      - name: Check Cargo.toml dependencies from workspace.dependencies
        run: cargo xtask check-cargo-dep-from-workspace

  test-win:
    name: Test (Windows)
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # By default actions/checkout checks out a merge commit. Check out the PR head instead.
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup env
        run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Install openssl
        run: vcpkg install openssl:x64-windows-static-md
      - name: Install rust
        run: rustup update nightly && rustup default nightly
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Print environment
        shell: pwsh
        run: |
          ls env:
      - name: Collect other system information
        run: |
          git --version
      - name: Compile xtask
        run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
      - name: Compile binaries and tests
        run: cargo xtask test --verbose --no-run
      - name: Run tests
        run: cargo xtask test --verbose --no-fail-fast

  test-linux:
    name: Test (Linux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # By default actions/checkout checks out a merge commit. Check out the PR head instead.
          # https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install lld
        run: sudo apt-get install -y lld
      - name: Install openssl
        run: sudo apt-get install -y libssl-dev
      - name: Install rust
        run: rustup update nightly && rustup default nightly
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Print environment
        run: |
          env
      - name: Collect other system information
        run: |
          git --version
      - name: Compile xtask
        run: cargo build -p upsilon-xtask --bin upsilon-xtask --verbose
      - name: Compile binaries and tests
        run: cargo xtask test --verbose --no-run
      - name: Run tests
        run: cargo xtask test --verbose --no-fail-fast
